# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowV2.ui'
#
# Created: Mon May 25 11:19:23 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 525)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gOscilloscope = DoubleYPlot(self.tab)
        self.gOscilloscope.setGeometry(QtCore.QRect(50, 10, 671, 271))
        self.gOscilloscope.setObjectName(_fromUtf8("gOscilloscope"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(90, 300, 105, 69))
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cChannelPicker = QtGui.QComboBox(self.groupBox_4)
        self.cChannelPicker.setObjectName(_fromUtf8("cChannelPicker"))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.cChannelPicker)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(260, 310, 105, 69))
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cChannelPickerRef = QtGui.QComboBox(self.groupBox_5)
        self.cChannelPickerRef.setObjectName(_fromUtf8("cChannelPickerRef"))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.cChannelPickerRef)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(440, 310, 128, 69))
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.cOscGPIB = QtGui.QComboBox(self.groupBox_6)
        self.cOscGPIB.setObjectName(_fromUtf8("cOscGPIB"))
        self.horizontalLayout_11.addWidget(self.cOscGPIB)
        self.bInitOsc = QtGui.QPushButton(self.tab)
        self.bInitOsc.setGeometry(QtCore.QRect(580, 300, 115, 32))
        self.bInitOsc.setObjectName(_fromUtf8("bInitOsc"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(200, 30, 511, 151))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gLeakage = PlotWidget(self.horizontalLayoutWidget)
        self.gLeakage.setObjectName(_fromUtf8("gLeakage"))
        self.horizontalLayout.addWidget(self.gLeakage)
        self.gValueVsV = PlotWidget(self.horizontalLayoutWidget)
        self.gValueVsV.setObjectName(_fromUtf8("gValueVsV"))
        self.horizontalLayout.addWidget(self.gValueVsV)
        self.widget = QtGui.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(220, 270, 427, 56))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tGateStart = QFNumberEdit(self.groupBox)
        self.tGateStart.setObjectName(_fromUtf8("tGateStart"))
        self.horizontalLayout_4.addWidget(self.tGateStart)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.widget)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tGateEnd = QFNumberEdit(self.groupBox_3)
        self.tGateEnd.setObjectName(_fromUtf8("tGateEnd"))
        self.horizontalLayout_3.addWidget(self.tGateEnd)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.widget)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tGateStep = QFNumberEdit(self.groupBox_2)
        self.tGateStep.setObjectName(_fromUtf8("tGateStep"))
        self.horizontalLayout_5.addWidget(self.tGateStep)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(470, 340, 155, 70))
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tMeasureEvery = QtGui.QLineEdit(self.groupBox_7)
        self.tMeasureEvery.setObjectName(_fromUtf8("tMeasureEvery"))
        self.horizontalLayout_7.addWidget(self.tMeasureEvery)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(100, 340, 155, 70))
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tSave = QtGui.QLineEdit(self.groupBox_8)
        self.tSave.setObjectName(_fromUtf8("tSave"))
        self.horizontalLayout_8.addWidget(self.tSave)
        self.bSaveDirectory = QtGui.QPushButton(self.tab_2)
        self.bSaveDirectory.setGeometry(QtCore.QRect(270, 380, 115, 32))
        self.bSaveDirectory.setObjectName(_fromUtf8("bSaveDirectory"))
        self.bStartScan = QtGui.QPushButton(self.tab_2)
        self.bStartScan.setGeometry(QtCore.QRect(30, 150, 115, 32))
        self.bStartScan.setObjectName(_fromUtf8("bStartScan"))
        self.bAbortScan = QtGui.QPushButton(self.tab_2)
        self.bAbortScan.setGeometry(QtCore.QRect(40, 210, 115, 32))
        self.bAbortScan.setObjectName(_fromUtf8("bAbortScan"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(190, 190, 128, 69))
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_12.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.cKeithGPIB = QtGui.QComboBox(self.groupBox_9)
        self.cKeithGPIB.setObjectName(_fromUtf8("cKeithGPIB"))
        self.horizontalLayout_12.addWidget(self.cKeithGPIB)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Signal Ch", None))
        self.cChannelPicker.setItemText(0, _translate("MainWindow", "CH1", None))
        self.cChannelPicker.setItemText(1, _translate("MainWindow", "CH2", None))
        self.cChannelPicker.setItemText(2, _translate("MainWindow", "CH3", None))
        self.cChannelPicker.setItemText(3, _translate("MainWindow", "CH4", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Ref Ch", None))
        self.cChannelPickerRef.setItemText(0, _translate("MainWindow", "CH1", None))
        self.cChannelPickerRef.setItemText(1, _translate("MainWindow", "CH2", None))
        self.cChannelPickerRef.setItemText(2, _translate("MainWindow", "CH3", None))
        self.cChannelPickerRef.setItemText(3, _translate("MainWindow", "CH4", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Osc GPIB", None))
        self.bInitOsc.setText(_translate("MainWindow", "Init Regions", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Oscilloscope", None))
        self.groupBox.setTitle(_translate("MainWindow", "Gate Start (V)", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gate End (V)", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Gate Step (V)", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Measure Every", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Save Name", None))
        self.bSaveDirectory.setText(_translate("MainWindow", "Choose Location", None))
        self.bStartScan.setText(_translate("MainWindow", "Start", None))
        self.bAbortScan.setText(_translate("MainWindow", "Abort", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Keithley GPIB", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan", None))

from pyqtgraph import PlotWidget
from InstsAndQt.customQt import DoubleYPlot, QFNumberEdit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

