# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dvalovcin\Documents\GitHub\HarvardCode\mainWindowV2.ui'
#
# Created: Mon Sep 07 15:05:23 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 691)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.splitter_2 = QtGui.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.gOscilloscopePyro = PlotWidget(self.splitter)
        self.gOscilloscopePyro.setObjectName(_fromUtf8("gOscilloscopePyro"))
        self.gOscilloscopeWave = PlotWidget(self.splitter)
        self.gOscilloscopeWave.setObjectName(_fromUtf8("gOscilloscopeWave"))
        self.tabWidget_2 = QtGui.QTabWidget(self.splitter_2)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_9.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cChannelPicker = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cChannelPicker.sizePolicy().hasHeightForWidth())
        self.cChannelPicker.setSizePolicy(sizePolicy)
        self.cChannelPicker.setObjectName(_fromUtf8("cChannelPicker"))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.cChannelPicker)
        self.horizontalLayout_13.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cChannelPickerRef = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cChannelPickerRef.sizePolicy().hasHeightForWidth())
        self.cChannelPickerRef.setSizePolicy(sizePolicy)
        self.cChannelPickerRef.setObjectName(_fromUtf8("cChannelPickerRef"))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.cChannelPickerRef.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.cChannelPickerRef)
        self.horizontalLayout_13.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_11.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.cOscGPIB = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.cOscGPIB.sizePolicy().hasHeightForWidth())
        self.cOscGPIB.setSizePolicy(sizePolicy)
        self.cOscGPIB.setObjectName(_fromUtf8("cOscGPIB"))
        self.horizontalLayout_11.addWidget(self.cOscGPIB)
        self.horizontalLayout_13.addWidget(self.groupBox_6)
        self.groupBox_14 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setFlat(True)
        self.groupBox_14.setCheckable(False)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tOAverages = QINumberEdit(self.groupBox_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tOAverages.sizePolicy().hasHeightForWidth())
        self.tOAverages.setSizePolicy(sizePolicy)
        self.tOAverages.setObjectName(_fromUtf8("tOAverages"))
        self.verticalLayout_3.addWidget(self.tOAverages)
        self.horizontalLayout_13.addWidget(self.groupBox_14)
        self.bOscPause = QtGui.QPushButton(self.tab_3)
        self.bOscPause.setCheckable(True)
        self.bOscPause.setObjectName(_fromUtf8("bOscPause"))
        self.horizontalLayout_13.addWidget(self.bOscPause)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_14.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.tPyroBGSt = QFNumberEdit(self.groupBox_10)
        self.tPyroBGSt.setObjectName(_fromUtf8("tPyroBGSt"))
        self.horizontalLayout_14.addWidget(self.tPyroBGSt)
        self.tPyroBGEn = QFNumberEdit(self.groupBox_10)
        self.tPyroBGEn.setObjectName(_fromUtf8("tPyroBGEn"))
        self.horizontalLayout_14.addWidget(self.tPyroBGEn)
        self.gridLayout.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_15.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.tPyroSGSt = QFNumberEdit(self.groupBox_11)
        self.tPyroSGSt.setObjectName(_fromUtf8("tPyroSGSt"))
        self.horizontalLayout_15.addWidget(self.tPyroSGSt)
        self.tPyroSGEn = QFNumberEdit(self.groupBox_11)
        self.tPyroSGEn.setObjectName(_fromUtf8("tPyroSGEn"))
        self.horizontalLayout_15.addWidget(self.tPyroSGEn)
        self.gridLayout.addWidget(self.groupBox_11, 0, 2, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_17.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.tWaveSGSt = QFNumberEdit(self.groupBox_13)
        self.tWaveSGSt.setObjectName(_fromUtf8("tWaveSGSt"))
        self.horizontalLayout_17.addWidget(self.tWaveSGSt)
        self.tWaveSGEn = QFNumberEdit(self.groupBox_13)
        self.tWaveSGEn.setObjectName(_fromUtf8("tWaveSGEn"))
        self.horizontalLayout_17.addWidget(self.tWaveSGEn)
        self.gridLayout.addWidget(self.groupBox_13, 1, 2, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_16.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.tWaveBGSt = QFNumberEdit(self.groupBox_12)
        self.tWaveBGSt.setObjectName(_fromUtf8("tWaveBGSt"))
        self.horizontalLayout_16.addWidget(self.tWaveBGSt)
        self.tWaveBGEn = QFNumberEdit(self.groupBox_12)
        self.tWaveBGEn.setObjectName(_fromUtf8("tWaveBGEn"))
        self.horizontalLayout_16.addWidget(self.tWaveBGEn)
        self.gridLayout.addWidget(self.groupBox_12, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout)
        self.bInitOsc = QtGui.QPushButton(self.tab_4)
        self.bInitOsc.setObjectName(_fromUtf8("bInitOsc"))
        self.horizontalLayout_18.addWidget(self.bInitOsc)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.splitter_4 = QtGui.QSplitter(self.tab_2)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.gLeakage = PlotWidget(self.splitter_3)
        self.gLeakage.setObjectName(_fromUtf8("gLeakage"))
        self.gValueVsV = PlotWidget(self.splitter_3)
        self.gValueVsV.setObjectName(_fromUtf8("gValueVsV"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.splitter_4)
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tGateStart = QFNumberEdit(self.groupBox)
        self.tGateStart.setObjectName(_fromUtf8("tGateStart"))
        self.horizontalLayout_4.addWidget(self.tGateStart)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tGateEnd = QFNumberEdit(self.groupBox_3)
        self.tGateEnd.setObjectName(_fromUtf8("tGateEnd"))
        self.horizontalLayout_3.addWidget(self.tGateEnd)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tGateStep = QFNumberEdit(self.groupBox_2)
        self.tGateStep.setObjectName(_fromUtf8("tGateStep"))
        self.horizontalLayout_5.addWidget(self.tGateStep)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_9 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_12.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.cKeithGPIB = QtGui.QComboBox(self.groupBox_9)
        self.cKeithGPIB.setObjectName(_fromUtf8("cKeithGPIB"))
        self.horizontalLayout_12.addWidget(self.cKeithGPIB)
        self.horizontalLayout_2.addWidget(self.groupBox_9)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_8 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.tSave = QtGui.QLineEdit(self.groupBox_8)
        self.tSave.setObjectName(_fromUtf8("tSave"))
        self.horizontalLayout_8.addWidget(self.tSave)
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.bSaveDirectory = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.bSaveDirectory.setObjectName(_fromUtf8("bSaveDirectory"))
        self.horizontalLayout.addWidget(self.bSaveDirectory)
        self.groupBox_7 = QtGui.QGroupBox(self.gridLayoutWidget_2)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.tMeasureEvery = QINumberEdit(self.groupBox_7)
        self.tMeasureEvery.setObjectName(_fromUtf8("tMeasureEvery"))
        self.horizontalLayout_7.addWidget(self.tMeasureEvery)
        self.horizontalLayout.addWidget(self.groupBox_7)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.bStartScan = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.bStartScan.setObjectName(_fromUtf8("bStartScan"))
        self.verticalLayout.addWidget(self.bStartScan)
        self.bAbortScan = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.bAbortScan.setObjectName(_fromUtf8("bAbortScan"))
        self.verticalLayout.addWidget(self.bAbortScan)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.bScanPause = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.bScanPause.setCheckable(True)
        self.bScanPause.setObjectName(_fromUtf8("bScanPause"))
        self.gridLayout_2.addWidget(self.bScanPause, 1, 1, 1, 1)
        self.horizontalLayout_19.addWidget(self.splitter_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Signal Ch", None))
        self.cChannelPicker.setItemText(0, _translate("MainWindow", "CH1", None))
        self.cChannelPicker.setItemText(1, _translate("MainWindow", "CH2", None))
        self.cChannelPicker.setItemText(2, _translate("MainWindow", "CH3", None))
        self.cChannelPicker.setItemText(3, _translate("MainWindow", "CH4", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Ref Ch", None))
        self.cChannelPickerRef.setItemText(0, _translate("MainWindow", "CH1", None))
        self.cChannelPickerRef.setItemText(1, _translate("MainWindow", "CH2", None))
        self.cChannelPickerRef.setItemText(2, _translate("MainWindow", "CH3", None))
        self.cChannelPickerRef.setItemText(3, _translate("MainWindow", "CH4", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Osc GPIB", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "Average", None))
        self.tOAverages.setText(_translate("MainWindow", "1", None))
        self.bOscPause.setText(_translate("MainWindow", "Pause", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Settings", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Pyro Background", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Pyro Signal", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Waveform Signal", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "Waveform Background", None))
        self.bInitOsc.setText(_translate("MainWindow", "Init Regions", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Integration Regions", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Oscilloscope", None))
        self.groupBox.setTitle(_translate("MainWindow", "Gate Start (V)", None))
        self.tGateStart.setText(_translate("MainWindow", "0.0", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Gate End (V)", None))
        self.tGateEnd.setText(_translate("MainWindow", "1", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Gate Step (V)", None))
        self.tGateStep.setText(_translate("MainWindow", "0.1", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Keithley GPIB", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Save Name", None))
        self.bSaveDirectory.setText(_translate("MainWindow", "Choose Location", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Measure Every", None))
        self.tMeasureEvery.setText(_translate("MainWindow", "1", None))
        self.bStartScan.setText(_translate("MainWindow", "Start", None))
        self.bAbortScan.setText(_translate("MainWindow", "Abort", None))
        self.bScanPause.setText(_translate("MainWindow", "Pause", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Scan", None))

from pyqtgraph import PlotWidget
from InstsAndQt.customQt import QINumberEdit, QFNumberEdit
