# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Darren\Python\ForHarvard\V2\mainWindow.ui'
#
# Created: Tue Jan 20 16:36:23 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1112, 766)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gLeakage = PlotWidget(self.centralwidget)
        self.gLeakage.setObjectName(_fromUtf8("gLeakage"))
        self.horizontalLayout.addWidget(self.gLeakage)
        self.gOscilloscope = PlotWidget(self.centralwidget)
        self.gOscilloscope.setObjectName(_fromUtf8("gOscilloscope"))
        self.horizontalLayout.addWidget(self.gOscilloscope)
        self.gValueVsV = PlotWidget(self.centralwidget)
        self.gValueVsV.setObjectName(_fromUtf8("gValueVsV"))
        self.horizontalLayout.addWidget(self.gValueVsV)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.tGateStart = QtGui.QLineEdit(self.centralwidget)
        self.tGateStart.setObjectName(_fromUtf8("tGateStart"))
        self.horizontalLayout_4.addWidget(self.tGateStart)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.tGateStep = QtGui.QLineEdit(self.centralwidget)
        self.tGateStep.setObjectName(_fromUtf8("tGateStep"))
        self.horizontalLayout_4.addWidget(self.tGateStep)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.tGateEnd = QtGui.QLineEdit(self.centralwidget)
        self.tGateEnd.setObjectName(_fromUtf8("tGateEnd"))
        self.horizontalLayout_4.addWidget(self.tGateEnd)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_5.addWidget(self.label_6)
        self.tIntStart = QtGui.QLineEdit(self.centralwidget)
        self.tIntStart.setObjectName(_fromUtf8("tIntStart"))
        self.horizontalLayout_5.addWidget(self.tIntStart)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.tIntEnd = QtGui.QLineEdit(self.centralwidget)
        self.tIntEnd.setObjectName(_fromUtf8("tIntEnd"))
        self.horizontalLayout_5.addWidget(self.tIntEnd)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.tMeasureEvery = QtGui.QLineEdit(self.centralwidget)
        self.tMeasureEvery.setObjectName(_fromUtf8("tMeasureEvery"))
        self.horizontalLayout_5.addWidget(self.tMeasureEvery)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.bStartScan = QtGui.QPushButton(self.centralwidget)
        self.bStartScan.setObjectName(_fromUtf8("bStartScan"))
        self.verticalLayout.addWidget(self.bStartScan)
        self.bAbortScan = QtGui.QPushButton(self.centralwidget)
        self.bAbortScan.setObjectName(_fromUtf8("bAbortScan"))
        self.verticalLayout.addWidget(self.bAbortScan)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.cChannelPicker = QtGui.QComboBox(self.centralwidget)
        self.cChannelPicker.setObjectName(_fromUtf8("cChannelPicker"))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.cChannelPicker.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cChannelPicker)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.tSave = QtGui.QLineEdit(self.centralwidget)
        self.tSave.setObjectName(_fromUtf8("tSave"))
        self.horizontalLayout_3.addWidget(self.tSave)
        self.bSaveDirectory = QtGui.QPushButton(self.centralwidget)
        self.bSaveDirectory.setObjectName(_fromUtf8("bSaveDirectory"))
        self.horizontalLayout_3.addWidget(self.bSaveDirectory)
        self.bResetLeak = QtGui.QPushButton(self.centralwidget)
        self.bResetLeak.setObjectName(_fromUtf8("bResetLeak"))
        self.horizontalLayout_3.addWidget(self.bResetLeak)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1112, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.mFileExit = QtGui.QAction(MainWindow)
        self.mFileExit.setObjectName(_fromUtf8("mFileExit"))
        self.mFileUpdate = QtGui.QAction(MainWindow)
        self.mFileUpdate.setObjectName(_fromUtf8("mFileUpdate"))
        self.menuFile.addAction(self.mFileUpdate)
        self.menuFile.addAction(self.mFileExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Gate Start (V):", None))
        self.label_2.setText(_translate("MainWindow", "Gate Step (V):", None))
        self.label_3.setText(_translate("MainWindow", "Gate End (V):", None))
        self.label_6.setText(_translate("MainWindow", "Int Start", None))
        self.tIntStart.setText(_translate("MainWindow", "7e-6", None))
        self.label_7.setText(_translate("MainWindow", "Int End", None))
        self.tIntEnd.setText(_translate("MainWindow", "20e-6", None))
        self.label_8.setText(_translate("MainWindow", "Measure Every", None))
        self.tMeasureEvery.setText(_translate("MainWindow", "1", None))
        self.bStartScan.setText(_translate("MainWindow", "Start", None))
        self.bAbortScan.setText(_translate("MainWindow", "Abort", None))
        self.label_5.setText(_translate("MainWindow", "Osc Channel:", None))
        self.cChannelPicker.setItemText(0, _translate("MainWindow", "CH1", None))
        self.cChannelPicker.setItemText(1, _translate("MainWindow", "CH2", None))
        self.cChannelPicker.setItemText(2, _translate("MainWindow", "CH3", None))
        self.cChannelPicker.setItemText(3, _translate("MainWindow", "CH4", None))
        self.label_4.setText(_translate("MainWindow", "Save name:", None))
        self.bSaveDirectory.setText(_translate("MainWindow", "Choose Location", None))
        self.bResetLeak.setText(_translate("MainWindow", "Reset Leak", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.mFileExit.setText(_translate("MainWindow", "Exit", None))
        self.mFileUpdate.setText(_translate("MainWindow", "Update Scope", None))

from pyqtgraph import PlotWidget
